export type Product = {
  id: string;
  product_name_en: string;
  product_name_zh: string;
  brand: string;
  category_en: string;
  category_zh: string;
  sub_category_en: string;
  sub_category_zh: string;
  aisle: string;
  shelf: string;
  section_en: string;
  section_zh: string;
  image_url: string;
};

export type SubCategory = {
  en: string;
  zh: string;
}

export type Category = {
  id: string;
  en: string;
  zh: string;
  icon: string;
  subCategories: SubCategory[];
}

export const CATEGORIES: Category[] = [
  { 
    id: 'fresh-fruits', 
    en: 'Fresh Fruits', 
    zh: '嚴選水果', 
    icon: 'Apple',
    subCategories: [
      { en: 'Tropical Fruits', zh: '熱帶水果' },
      { en: 'Apples & Pears', zh: '蘋果與梨' },
      { en: 'Berries & Grapes', zh: '莓果與葡萄' },
      { en: 'Citrus Fruits', zh: '柑橘果類' },
      { en: 'Frozen Fruits', zh: '冷凍水果' },
    ]
  },
  { 
    id: 'fresh-vegetables', 
    en: 'Fresh Vegetables', 
    zh: '嚴選蔬菜', 
    icon: 'Carrot',
    subCategories: [
      { en: 'Legume & Melons', zh: '豆菜瓜果' },
      { en: 'Leaf & Flower Crops', zh: '葉菜花菜' },
      { en: 'Root & Stem Vegetables', zh: '根莖類' },
      { en: 'Mushroom & Fungi', zh: '蕈菇類' },
      { en: 'Herb & Spices', zh: '辛香蔥蒜' },
      { en: 'Frozen Vegetables', zh: '冷凍蔬菜' },
      { en: 'Other Vegetables', zh: '其他蔬菜' },
    ]
  },
  { 
    id: 'meat-seafood', 
    en: 'Meat & Seafood', 
    zh: '肉品海鮮', 
    icon: 'Beef',
    subCategories: [
      { en: 'Frozen Beef & Lamb', zh: '冷凍牛羊' },
      { en: 'Fresh Beef & Lamb', zh: '冷藏牛羊' },
      { en: 'Frozen Pork', zh: '冷凍豬肉' },
      { en: 'Fresh Pork', zh: '冷藏豬肉' },
      { en: 'Frozen Poultry', zh: '冷凍禽肉' },
      { en: 'Fresh Poultry', zh: '冷藏禽肉' },
      { en: 'Fish', zh: '魚類' },
      { en: 'Other Seafood', zh: '其他海鮮' },
      { en: 'Ham, Bacon & Sausage', zh: '加工肉品' },
    ]
  },
  { 
    id: 'dairy-eggs', 
    en: 'Dairy & Eggs', 
    zh: '乳品豆製品蛋', 
    icon: 'Egg',
    subCategories: [
      { en: 'Eggs', zh: '蛋' },
      { en: 'Butter & Cheese', zh: '乳製品' },
      { en: 'Milk', zh: '牛奶' },
      { en: 'Rice & Soy Drinks', zh: '豆漿米漿' },
      { en: 'Flavored Milk', zh: '調味乳' },
      { en: 'Probiotic Milk', zh: '乳酸飲' },
      { en: 'Preserved Milk', zh: '保久乳' },
      { en: 'Oat Drinks', zh: '燕麥奶及植物奶' },
      { en: 'Yogurt', zh: '優格' },
      { en: 'Preserved Eggs', zh: '加工蛋' },
      { en: 'Bean Products', zh: '豆類製品' },
    ]
  },
  { 
    id: 'beverages', 
    en: 'Beverages', 
    zh: '飲品大賞', 
    icon: 'CupSoda',
    subCategories: [
      { en: 'Soda', zh: '碳酸飲品' },
      { en: 'Coffee', zh: '咖啡' },
      { en: 'Sports & Energy Drinks', zh: '運動飲料及能量飲' },
      { en: 'Water', zh: '水' },
      { en: 'Sparkling Water', zh: '氣泡水' },
      { en: 'Vegetable & Fruit Juice', zh: '蔬果汁及果醋' },
      { en: 'Regular Pure Tea', zh: '茶飲' },
      { en: 'Unsweetened Pure Tea', zh: '無糖茶' },
      { en: 'Flavored Tea Drinks', zh: '調味茶飲' },
    ]
  },
  { 
    id: 'rice-noodles-grains', 
    en: 'Rice, Noodles & Grains', 
    zh: '米麵雜糧', 
    icon: 'Utensils',
    subCategories: [
      { en: 'White Rice', zh: '白米' },
      { en: 'Other Rice & Grains', zh: '糙米五穀' },
      { en: 'Noodles', zh: '麵條' },
      { en: 'Pasta', zh: '義大利麵' },
      { en: 'Other Grains', zh: '其他南北貨' },
      { en: 'Taiwanese Instant Noodles Cup & Bowls', zh: '台灣碗裝泡麵' },
      { en: 'Taiwanese Instant Noodles Packs', zh: '台灣袋裝泡麵' },
      { en: 'Imported Instant Noodles Cups & Bowls', zh: '進口碗裝泡麵' },
      { en: 'Imported Instant Noodles Packs', zh: '進口袋裝泡麵' },
    ]
  },
  { 
    id: 'frozen', 
    en: 'Frozen', 
    zh: '冷凍冷藏', 
    icon: 'Snowflake',
    subCategories: [
      { en: 'Frozen Dumplings & Wontons', zh: '餃子餛飩' },
      { en: 'Frozen Meals', zh: '調理食品' },
      { en: 'Ice Cream', zh: '冰品' },
      { en: 'Frozen Fried Food', zh: '冷凍炸物' },
      { en: 'Frozen Dough & Pastries', zh: '包子饅頭餅' },
      { en: 'Frozen Hot Pot Ingredients', zh: '火鍋料' },
      { en: 'Frozen Hot Pot Soup Base', zh: '火鍋湯底' },
      { en: 'Frozen Heat and Eat Meals', zh: '冷凍調理' },
      { en: 'Frozen Desserts', zh: '湯圓甜品' },
      { en: 'Chilled Desserts', zh: '冷藏甜點' },
    ]
  },
  { 
    id: 'snacks-candies', 
    en: 'Snacks & Candies', 
    zh: '零食餅乾', 
    icon: 'Cookie',
    subCategories: [
      { en: 'Soft Candy', zh: '軟糖' },
      { en: 'Hard Candy', zh: '硬糖' },
      { en: 'Chocolates', zh: '巧克力' },
      { en: 'Gum & Mints', zh: '口香糖及涼糖' },
      { en: 'Chips', zh: '洋芋片' },
      { en: 'Salty Crackers', zh: '蘇打餅' },
      { en: 'Seaweed & Seafood Snacks', zh: '海苔' },
      { en: 'Nuts', zh: '堅果及瓜子' },
      { en: 'Crackers', zh: '鹹餅乾' },
      { en: 'Other Desserts & Cookies', zh: '甜零食' },
      { en: 'Sandwich Biscuits', zh: '夾心餅乾' },
      { en: 'Rolled Wafer', zh: '捲心酥' },
      { en: 'Rice Crackers & Rice Snacks', zh: '米餅米果' },
      { en: 'Dried Tofu & Jerky', zh: '豆干肉乾' },
      { en: 'Preserved & Dried Fruit Snacks', zh: '蜜餞果乾' },
      { en: 'Jelly & Pudding', zh: '果凍布丁' },
    ]
  },
  { 
    id: 'oil-condiments', 
    en: 'Oil & Condiments', 
    zh: '油品調味', 
    icon: 'FlaskConical', 
    subCategories: [
      { en: 'Cooking & Baking Powders', zh: '烘焙材料' },
      { en: 'Jams & Spreads', zh: '塗醬' },
      { en: 'Curry', zh: '咖哩' },
      { en: 'Other Edible Oils', zh: '其他食用油' },
      { en: 'Olive Oil', zh: '橄欖油' },
      { en: 'Flavored Oil', zh: '調味油品' },
      { en: 'Seasoning Powders', zh: '調味粉' },
      { en: 'Flavored Vinegars', zh: '風味醋類' },
      { en: 'Chili Sauce & Doubanjiang', zh: '辣椒豆瓣' },
      { en: 'Salad Dressing & Mayonnaise', zh: '沙拉美乃滋' },
      { en: 'BBQ Sauces', zh: '烤肉醬' },
      { en: 'Soy Sauces', zh: '醬油油膏' },
      { en: 'Sugar & Salt', zh: '鹽糖味精' },
      { en: 'Other Seasonings', zh: '其他調味' },
      { en: 'Other Sauces', zh: '其他醬料' },
      { en: 'Broth & Soup Base', zh: '湯塊湯包' },
    ]
  },
  { 
    id: 'disposables', 
    en: 'Disposables', 
    zh: '紙棉製品', 
    icon: 'ScrollText',
    subCategories: [
      { en: 'Tissue Papers', zh: '衛生紙' },
      { en: 'Wipes', zh: '濕紙巾' },
      { en: 'Sanitary Pads & Tampons', zh: '衛生棉與棉條' },
      { en: 'Sanitary Pads', zh: '衛生棉' },
      { en: 'Kitchen Towels', zh: '廚房紙巾' },
      { en: 'Pantyliners', zh: '護墊' },
      { en: 'Adult Diapers', zh: '成人尿布' },
    ]
  },
  { 
    id: 'seasoned-preserves', 
    en: 'Seasoned Preserves & Canned Goods', 
    zh: '食品罐頭', 
    icon: 'Container', 
    subCategories: [
      { en: 'Canned Goods', zh: '罐頭' },
      { en: 'Soup & Porridge', zh: '沖泡湯品及粥品' },
      { en: 'Sweet Soup', zh: '甜湯' },
    ]
  },
  { 
    id: 'cleaning-laundry', 
    en: 'Cleaning & Laundry', 
    zh: '家用清潔', 
    icon: 'SprayCan',
    subCategories: [
      { en: 'Laundry Supplies', zh: '衣物洗護' },
      { en: 'Kitchen Cleaning', zh: '廚房清潔' },
      { en: 'Bathroom Cleaning', zh: '衛浴清潔' },
      { en: 'Cleaning Supplies', zh: '清潔用品' },
      { en: 'Deodorizer & Dehumidifier', zh: '芳香及除溼' },
      { en: 'Pest Control', zh: '驅蚊防蟲' },
      { en: 'Plastic Bags', zh: '塑膠袋' },
    ]
  },
  { 
    id: 'instant-beverages', 
    en: 'Instant Beverages', 
    zh: '沖調飲品', 
    icon: 'Coffee',
    subCategories: [
      { en: 'Instant Coffee', zh: '沖泡咖啡' },
      { en: 'Instant Tea & Tea Bags', zh: '茶包及茶葉' },
      { en: 'Instant Cereals', zh: '沖泡麥片' },
      { en: 'Powdered Drinks', zh: '沖泡營養' },
      { en: 'Drip Coffee Bags', zh: '濾掛咖啡' },
      { en: 'Specialty Tea Blends', zh: '特調茶品' },
      { en: 'Adult Milk Powder', zh: '成人奶粉' },
      { en: 'Adult Nutritional Supplements', zh: '營養補充' },
    ]
  },
  { 
    id: 'personal-care', 
    en: 'Personal Care', 
    zh: '美妝個清', 
    icon: 'Sparkles',
    subCategories: [
      { en: 'Body Care', zh: '身體清潔' },
      { en: 'Body Treatment', zh: '身體保養' },
      { en: 'Toothbrush', zh: '牙刷' },
      { en: 'Toothpaste', zh: '牙膏' },
      { en: 'Other Oral Products', zh: '漱口水及其他口腔清潔' },
      { en: 'Facial Products', zh: '面部護理' },
      { en: 'Hand & Foot Products', zh: '手足護理' },
      { en: 'Sunscreen & Antiperspirant', zh: '防曬及止汗劑' },
      { en: 'Cosmetics & Beauty Accessories', zh: '美妝用品' },
      { en: 'Hair Products', zh: '美髮造型' },
      { en: 'Men Care', zh: '男性保養' },
    ]
  },
  { 
    id: 'pet-supplies', 
    en: 'Pet Supplies', 
    zh: '寵物用品', 
    icon: 'Dog',
    subCategories: [
      { en: 'Dog Food', zh: '狗飼料/罐頭' },
      { en: 'Cat Food', zh: '貓飼料/罐頭' },
      { en: 'Pet Treats', zh: '寵物零食' },
      { en: 'Other Pet Supplies', zh: '其他寵物用品' },
    ]
  },
  { 
    id: 'bakery', 
    en: 'Bakery', 
    zh: '烘焙點心', 
    icon: 'Croissant',
    subCategories: [
      { en: 'Breads', zh: '麵包' },
      { en: 'Toasts', zh: '吐司' },
      { en: 'Cakes & Desserts', zh: '蛋糕甜點' },
    ]
  },
  { 
    id: 'kitchen-dining', 
    en: 'Kitchen & Dining', 
    zh: '餐廚用品', 
    icon: 'ChefHat',
    subCategories: [
      { en: 'Cooking & Baking Utensils', zh: '烹飪及烘焙用具' },
      { en: 'Dining Utensils', zh: '碗盤餐具' },
      { en: 'Disposable Tablewares', zh: '免洗餐具' },
      { en: 'Wrappers, Bento & Bottles', zh: '保鮮用品' },
    ]
  },
  { 
    id: 'ready-to-eat', 
    en: 'Ready to Eat', 
    zh: '熟食專區', 
    icon: 'UtensilsCrossed',
    subCategories: [
      { en: 'Rice & Noodles (Ready To Eat)', zh: '米飯麵食' },
      { en: 'Snacks (Ready To Eat)', zh: '小吃點心' },
    ]
  },
  { 
    id: 'health-medical', 
    en: 'Health & Medical', 
    zh: '醫用保健', 
    icon: 'Stethoscope', 
    subCategories: [
      { en: 'First Aid Supplies', zh: '醫護常備' },
      { en: 'Health Supplements', zh: '保健食品' },
      { en: 'Health Drinks', zh: '保健飲品' },
      { en: 'Sexual Wellness', zh: '成人用品' },
    ]
  },
  { 
    id: 'nursery-care', 
    en: 'Nursery Care', 
    zh: '母嬰用品', 
    icon: 'Baby',
    subCategories: [
      { en: 'Baby Care Products', zh: '嬰幼兒護理' },
      { en: 'Baby Diapers', zh: '嬰幼兒尿布' },
      { en: 'Baby Food', zh: '嬰幼兒食品' },
      { en: 'Baby Formula', zh: '幼兒奶粉' },
    ]
  },
  { 
    id: 'home-office', 
    en: 'Home & Office Goods', 
    zh: '日用百貨', 
    icon: 'Armchair',
    subCategories: [
      { en: 'Batteries', zh: '充電及電池' },
      { en: 'Home Improvements', zh: '居家用品' },
      { en: 'Stationery & Office Supplies', zh: '辦公文具' },
      { en: 'Outdoor & Travels', zh: '旅行用品' },
      { en: 'Other Supplies', zh: '其他用品' },
    ]
  },
  { 
    id: 'clothing', 
    en: 'Clothing & Accessories', 
    zh: '服飾配件', 
    icon: 'Shirt',
    subCategories: [
      { en: 'Clothes', zh: '衣物' },
      { en: 'Underwears', zh: '貼身衣物' },
      { en: 'Socks', zh: '襪子' },
      { en: 'Bags', zh: '包包' },
    ]
  },
  { 
    id: 'gift-box', 
    en: 'Gift Box', 
    zh: '伴手禮與禮盒', 
    icon: 'Gift',
    subCategories: [
      { en: 'Performance Gift Box', zh: '保健品禮盒' },
    ]
  },
];

export const PRODUCTS: Product[] = [
  // Fresh Fruits
  {
    id: "f1",
    product_name_en: "Taiwan Banana",
    product_name_zh: "台灣香蕉",
    brand: "PX Select",
    category_en: "Fresh Fruits",
    category_zh: "嚴選水果",
    sub_category_en: "Tropical Fruits",
    sub_category_zh: "熱帶水果",
    aisle: "1",
    shelf: "1",
    section_en: "Fruits",
    section_zh: "水果區",
    image_url: "https://images.unsplash.com/photo-1571771896612-61871f0c2a8e?w=400&q=80",
  },
  {
    id: "f2",
    product_name_en: "Fuji Apple",
    product_name_zh: "富士蘋果",
    brand: "Imported",
    category_en: "Fresh Fruits",
    category_zh: "嚴選水果",
    sub_category_en: "Apples & Pears",
    sub_category_zh: "蘋果與梨",
    aisle: "1",
    shelf: "2",
    section_en: "Fruits",
    section_zh: "水果區",
    image_url: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&q=80",
  },
  {
    id: "f3",
    product_name_en: "Fresh Strawberries",
    product_name_zh: "新鮮草莓",
    brand: "Local Farm",
    category_en: "Fresh Fruits",
    category_zh: "嚴選水果",
    sub_category_en: "Berries & Grapes",
    sub_category_zh: "莓果與葡萄",
    aisle: "1",
    shelf: "Refrigerated",
    section_en: "Fruits",
    section_zh: "水果區",
    image_url: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80",
  },
  // Fresh Vegetables
  {
    id: "v1",
    product_name_en: "Organic Spinach",
    product_name_zh: "有機菠菜",
    brand: "PX Organic",
    category_en: "Fresh Vegetables",
    category_zh: "嚴選蔬菜",
    sub_category_en: "Leaf & Flower Crops",
    sub_category_zh: "葉菜花菜",
    aisle: "2",
    shelf: "1",
    section_en: "Vegetables",
    section_zh: "蔬菜區",
    image_url: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80",
  },
  {
    id: "v2",
    product_name_en: "Carrots",
    product_name_zh: "胡蘿蔔",
    brand: "PX Fresh",
    category_en: "Fresh Vegetables",
    category_zh: "嚴選蔬菜",
    sub_category_en: "Root & Stem Vegetables",
    sub_category_zh: "根莖類",
    aisle: "2",
    shelf: "2",
    section_en: "Vegetables",
    section_zh: "蔬菜區",
    image_url: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80",
  },
  // Meat & Seafood
  {
    id: "m1",
    product_name_en: "US Beef Short Ribs",
    product_name_zh: "美國牛小排",
    brand: "PX Choice",
    category_en: "Meat & Seafood",
    category_zh: "肉品海鮮",
    sub_category_en: "Frozen Beef & Lamb",
    sub_category_zh: "冷凍牛羊",
    aisle: "9",
    shelf: "Freezer 1",
    section_en: "Meat",
    section_zh: "肉品區",
    image_url: "https://images.unsplash.com/photo-1603048297172-c92544798d5e?w=400&q=80",
  },
  {
    id: "m2",
    product_name_en: "Fresh Salmon Fillet",
    product_name_zh: "新鮮鮭魚切片",
    brand: "Ocean Catch",
    category_en: "Meat & Seafood",
    category_zh: "肉品海鮮",
    sub_category_en: "Fish",
    sub_category_zh: "魚類",
    aisle: "9",
    shelf: "Refrigerated",
    section_en: "Seafood",
    section_zh: "海鮮區",
    image_url: "https://images.unsplash.com/photo-1599084993091-1a820b2e6b95?w=400&q=80",
  },
  // Dairy & Eggs
  {
    id: "d1",
    product_name_en: "Fresh Milk 2L",
    product_name_zh: "全脂鮮乳 2L",
    brand: "Dr. Milker",
    category_en: "Dairy & Eggs",
    category_zh: "乳品豆製品蛋",
    sub_category_en: "Milk",
    sub_category_zh: "牛奶",
    aisle: "10",
    shelf: "Refrigerated",
    section_en: "Dairy",
    section_zh: "乳品區",
    image_url: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&q=80",
  },
  {
    id: "d2",
    product_name_en: "Organic Eggs (10pcs)",
    product_name_zh: "有機雞蛋 (10入)",
    brand: "Happy Farm",
    category_en: "Dairy & Eggs",
    category_zh: "乳品豆製品蛋",
    sub_category_en: "Eggs",
    sub_category_zh: "蛋",
    aisle: "10",
    shelf: "1",
    section_en: "Dairy",
    section_zh: "乳品區",
    image_url: "https://images.unsplash.com/photo-1582722878654-0246bbc2998c?w=400&q=80",
  },
  // Beverages
  {
    id: "b1",
    product_name_en: "Coca Cola 330ml",
    product_name_zh: "可口可樂 330ml",
    brand: "Coca Cola",
    category_en: "Beverages",
    category_zh: "飲品大賞",
    sub_category_en: "Soda",
    sub_category_zh: "碳酸飲品",
    aisle: "4",
    shelf: "1",
    section_en: "Drinks",
    section_zh: "飲料區",
    image_url: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
  },
  {
    id: "b2",
    product_name_en: "Green Tea No Sugar",
    product_name_zh: "無糖綠茶",
    brand: "Chai Li Won",
    category_en: "Beverages",
    category_zh: "飲品大賞",
    sub_category_en: "Unsweetened Pure Tea",
    sub_category_zh: "無糖茶",
    aisle: "4",
    shelf: "2",
    section_en: "Drinks",
    section_zh: "飲料區",
    image_url: "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=400&q=80",
  },
  // Rice & Noodles
  {
    id: "r1",
    product_name_en: "Thai Jasmine Rice 5kg",
    product_name_zh: "泰國茉莉香米 5kg",
    brand: "Royal Umbrella",
    category_en: "Rice, Noodles & Grains",
    category_zh: "米麵雜糧",
    sub_category_en: "White Rice",
    sub_category_zh: "白米",
    aisle: "8",
    shelf: "1",
    section_en: "Grains",
    section_zh: "米糧區",
    image_url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
  },
  {
    id: "r2",
    product_name_en: "Instant Noodles Beef Flavor",
    product_name_zh: "牛肉麵泡麵",
    brand: "Uni-President",
    category_en: "Rice, Noodles & Grains",
    category_zh: "米麵雜糧",
    sub_category_en: "Taiwanese Instant Noodles Packs",
    sub_category_zh: "台灣袋裝泡麵",
    aisle: "8",
    shelf: "3",
    section_en: "Instant Noodles",
    section_zh: "泡麵區",
    image_url: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=400&q=80",
  },
  // Frozen
  {
    id: "fr1",
    product_name_en: "Pork Dumplings",
    product_name_zh: "豬肉水餃",
    brand: "Chi Mei",
    category_en: "Frozen",
    category_zh: "冷凍冷藏",
    sub_category_en: "Frozen Dumplings & Wontons",
    sub_category_zh: "餃子餛飩",
    aisle: "11",
    shelf: "Freezer 2",
    section_en: "Frozen Food",
    section_zh: "冷凍區",
    image_url: "https://images.unsplash.com/photo-1541696490-8744a5dc0228?w=400&q=80",
  },
  {
    id: "fr2",
    product_name_en: "Vanilla Ice Cream",
    product_name_zh: "香草冰淇淋",
    brand: "Haagen-Dazs",
    category_en: "Frozen",
    category_zh: "冷凍冷藏",
    sub_category_en: "Ice Cream",
    sub_category_zh: "冰品",
    aisle: "11",
    shelf: "Freezer 3",
    section_en: "Frozen Food",
    section_zh: "冷凍區",
    image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80",
  },
  // Snacks
  {
    id: "s1",
    product_name_en: "Potato Chips Original",
    product_name_zh: "原味洋芋片",
    brand: "Lay's",
    category_en: "Snacks & Candies",
    category_zh: "零食餅乾",
    sub_category_en: "Chips",
    sub_category_zh: "洋芋片",
    aisle: "6",
    shelf: "2",
    section_en: "Snacks",
    section_zh: "零食區",
    image_url: "https://images.unsplash.com/photo-1566478919030-41567d132720?w=400&q=80",
  },
  {
    id: "s2",
    product_name_en: "Dark Chocolate 70%",
    product_name_zh: "70% 黑巧克力",
    brand: "Lindt",
    category_en: "Snacks & Candies",
    category_zh: "零食餅乾",
    sub_category_en: "Chocolates",
    sub_category_zh: "巧克力",
    aisle: "6",
    shelf: "4",
    section_en: "Snacks",
    section_zh: "零食區",
    image_url: "https://images.unsplash.com/photo-1511381939415-e44015466834?w=400&q=80",
  },
  // Oil & Condiments
  {
    id: "o1",
    product_name_en: "Extra Virgin Olive Oil",
    product_name_zh: "特級初榨橄欖油",
    brand: "Olitalia",
    category_en: "Oil & Condiments",
    category_zh: "油品調味",
    sub_category_en: "Olive Oil",
    sub_category_zh: "橄欖油",
    aisle: "5",
    shelf: "1",
    section_en: "Condiments",
    section_zh: "調味區",
    image_url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&q=80",
  },
  {
    id: "o2",
    product_name_en: "Soy Sauce",
    product_name_zh: "醬油",
    brand: "Kikkoman",
    category_en: "Oil & Condiments",
    category_zh: "油品調味",
    sub_category_en: "Soy Sauces",
    sub_category_zh: "醬油油膏",
    aisle: "5",
    shelf: "2",
    section_en: "Condiments",
    section_zh: "調味區",
    image_url: "https://images.unsplash.com/photo-1626807255348-58fb844139b1?w=400&q=80",
  },
  // Disposables
  {
    id: "dp1",
    product_name_en: "Facial Tissue 120s",
    product_name_zh: "抽取式衛生紙 120抽",
    brand: "Kleenex",
    category_en: "Disposables",
    category_zh: "紙棉製品",
    sub_category_en: "Tissue Papers",
    sub_category_zh: "衛生紙",
    aisle: "12",
    shelf: "1",
    section_en: "Household",
    section_zh: "日用品區",
    image_url: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=400&q=80",
  },
  // Seasoned Preserves
  {
    id: "sp1",
    product_name_en: "Canned Corn",
    product_name_zh: "玉米粒罐頭",
    brand: "Green Giant",
    category_en: "Seasoned Preserves & Canned Goods",
    category_zh: "食品罐頭",
    sub_category_en: "Canned Goods",
    sub_category_zh: "罐頭",
    aisle: "5",
    shelf: "3",
    section_en: "Canned Food",
    section_zh: "罐頭區",
    image_url: "https://images.unsplash.com/photo-1621315271770-31d6cb524452?w=400&q=80",
  },
  // Cleaning & Laundry
  {
    id: "cl1",
    product_name_en: "Laundry Detergent",
    product_name_zh: "洗衣精",
    brand: "Ariel",
    category_en: "Cleaning & Laundry",
    category_zh: "家用清潔",
    sub_category_en: "Laundry Supplies",
    sub_category_zh: "衣物洗護",
    aisle: "12",
    shelf: "2",
    section_en: "Cleaning",
    section_zh: "清潔區",
    image_url: "https://images.unsplash.com/photo-1585670149967-b4f4da88cc9f?w=400&q=80",
  },
  // Instant Beverages
  {
    id: "ib1",
    product_name_en: "Instant Coffee Jar",
    product_name_zh: "即溶咖啡罐裝",
    brand: "Nescafe",
    category_en: "Instant Beverages",
    category_zh: "沖調飲品",
    sub_category_en: "Instant Coffee",
    sub_category_zh: "沖泡咖啡",
    aisle: "5",
    shelf: "4",
    section_en: "Coffee & Tea",
    section_zh: "沖泡區",
    image_url: "https://images.unsplash.com/photo-1610632380989-680fe40816c6?w=400&q=80",
  },
  // Personal Care
  {
    id: "pc1",
    product_name_en: "Shampoo Repair",
    product_name_zh: "修護洗髮精",
    brand: "Pantene",
    category_en: "Personal Care",
    category_zh: "美妝個清",
    sub_category_en: "Hair Products",
    sub_category_zh: "美髮造型",
    aisle: "13",
    shelf: "1",
    section_en: "Personal Care",
    section_zh: "個人護理區",
    image_url: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400&q=80",
  },
  // Pet Supplies
  {
    id: "ps1",
    product_name_en: "Dry Dog Food 1.5kg",
    product_name_zh: "乾狗糧 1.5kg",
    brand: "Pedigree",
    category_en: "Pet Supplies",
    category_zh: "寵物用品",
    sub_category_en: "Dog Food",
    sub_category_zh: "狗飼料/罐頭",
    aisle: "14",
    shelf: "1",
    section_en: "Pets",
    section_zh: "寵物區",
    image_url: "https://images.unsplash.com/photo-1585499193151-0f50d54c4e5d?w=400&q=80",
  },
  // Bakery
  {
    id: "bk1",
    product_name_en: "Sliced Bread",
    product_name_zh: "白吐司",
    brand: "PX Bakery",
    category_en: "Bakery",
    category_zh: "烘焙點心",
    sub_category_en: "Toasts",
    sub_category_zh: "吐司",
    aisle: "1",
    shelf: "3",
    section_en: "Bakery",
    section_zh: "烘焙區",
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80",
  },
  // Kitchen & Dining
  {
    id: "kd1",
    product_name_en: "Frying Pan 28cm",
    product_name_zh: "不沾平底鍋 28cm",
    brand: "Tefal",
    category_en: "Kitchen & Dining",
    category_zh: "餐廚用品",
    sub_category_en: "Cooking & Baking Utensils",
    sub_category_zh: "烹飪及烘焙用具",
    aisle: "15",
    shelf: "1",
    section_en: "Kitchenware",
    section_zh: "廚具區",
    image_url: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=400&q=80",
  },
  // Ready to Eat
  {
    id: "re1",
    product_name_en: "Bento Box Chicken",
    product_name_zh: "雞腿便當",
    brand: "PX Kitchen",
    category_en: "Ready to Eat",
    category_zh: "熟食專區",
    sub_category_en: "Rice & Noodles (Ready To Eat)",
    sub_category_zh: "米飯麵食",
    aisle: "1",
    shelf: "Hot Food",
    section_en: "Deli",
    section_zh: "熟食區",
    image_url: "https://images.unsplash.com/photo-1606335543042-57c525922933?w=400&q=80",
  },
  // Health & Medical
  {
    id: "hm1",
    product_name_en: "Vitamin C Tablets",
    product_name_zh: "維他命 C 錠",
    brand: "DHC",
    category_en: "Health & Medical",
    category_zh: "醫用保健",
    sub_category_en: "Health Supplements",
    sub_category_zh: "保健食品",
    aisle: "13",
    shelf: "3",
    section_en: "Pharmacy",
    section_zh: "藥妝區",
    image_url: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80",
  },
  // Nursery Care
  {
    id: "nc1",
    product_name_en: "Baby Diapers Size M",
    product_name_zh: "嬰兒紙尿褲 M號",
    brand: "Pampers",
    category_en: "Nursery Care",
    category_zh: "母嬰用品",
    sub_category_en: "Baby Diapers",
    sub_category_zh: "嬰幼兒尿布",
    aisle: "14",
    shelf: "2",
    section_en: "Baby",
    section_zh: "嬰兒區",
    image_url: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&q=80",
  },
  // Home & Office
  {
    id: "ho1",
    product_name_en: "AA Batteries 4pcs",
    product_name_zh: "AA 電池 4入",
    brand: "Duracell",
    category_en: "Home & Office Goods",
    category_zh: "日用百貨",
    sub_category_en: "Batteries",
    sub_category_zh: "充電及電池",
    aisle: "15",
    shelf: "2",
    section_en: "Household",
    section_zh: "百貨區",
    image_url: "https://images.unsplash.com/photo-1618422680437-54365588227b?w=400&q=80",
  },
  // Clothing
  {
    id: "clt1",
    product_name_en: "Cotton T-Shirt White",
    product_name_zh: "純棉T恤 白色",
    brand: "Basic",
    category_en: "Clothing & Accessories",
    category_zh: "服飾配件",
    sub_category_en: "Clothes",
    sub_category_zh: "衣物",
    aisle: "16",
    shelf: "1",
    section_en: "Apparel",
    section_zh: "服飾區",
    image_url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80",
  },
  // Gift Box
  {
    id: "gb1",
    product_name_en: "Chicken Essence Gift Box",
    product_name_zh: "雞精禮盒",
    brand: "Brand's",
    category_en: "Gift Box",
    category_zh: "伴手禮與禮盒",
    sub_category_en: "Performance Gift Box",
    sub_category_zh: "保健品禮盒",
    aisle: "3",
    shelf: "1",
    section_en: "Gifts",
    section_zh: "禮盒區",
    image_url: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=400&q=80",
  }
];
